'use client';

import { useEffect, useState } from 'react';
import { ArrowDown, ArrowRight, BatteryCharging, Check, ChevronDown, Droplets, Gauge, MapPin, Menu, MessageCircle, ShieldCheck, Waves, Wind, X } from 'lucide-react';

type Lang = 'hr' | 'en' | 'de';
type Size = 'small' | 'medium' | 'large';

const prices = {
  Watch: { small: 80, medium: 100, large: 120 },
  Care: { small: 160, medium: 200, large: 240 },
  Guard: { small: 290, medium: 360, large: 430 },
};

const content = {
  hr: {
    nav: ['Kako radi', 'Paketi', 'O nama', 'FAQ'], eyebrow: 'Briga o brodu u Puli i južnoj Istri',
    hero: 'Netko provjerava vaš brod. I kad vi niste ovdje.', intro: 'Filip obilazi vaš brod, provjerava dogovorene stavke i šalje fotografije nakon svakog dolaska. Vi znate što se događa, bez putovanja do marine.',
    primary: 'Dogovorite prvi pregled', secondary: 'Pogledajte pakete', trust: ['Pula, Veruda, Bunarina i Medulin', 'Dostupno cijele godine', 'Fotografije nakon obilaska'], status: 'Izvještaj poslan vlasniku',
    problemK: 'Dok ste daleko', problemT: 'Brod ne miruje samo zato što je vezan.', problemB: 'Kiša napuni kaljužu. Akumulator oslabi. Konop se olabavi. Redoviti pregled znači da takve promjene vidimo dok ih je još jednostavno riješiti.',
    processK: 'Kako servis radi', processT: 'Znate kada dolazimo, što gledamo i što smo zatekli.', steps: [['01','Prvi pregled','Upoznajemo brod, vez i ono što vam je važno.'],['02','Ritam obilazaka','Jedan, dva ili četiri dolaska mjesečno, ovisno o paketu.'],['03','Provjera i fotografije','Nakon svakog obilaska šaljemo kratak, razumljiv izvještaj.'],['04','Dogovor prije radova','Ako nešto treba riješiti, javljamo se prije dodatnog troška.']],
    checksK: 'Kontrolna lista', checksT: 'Svaki obilazak ima smisao.', checks: [['Kaljuža i voda','Gledamo ima li vode ili znakova prodora.','water'],['Vlaga i pokrov','Provjeravamo kondenzaciju, apsorbere i pokrov.','wind'],['Akumulator','Provjeravamo stanje prema dogovorenom paketu.','battery'],['Vez i bokobrani','Pregledavamo konope, bokobrane i položaj broda.','waves'],['Motor','Pokrećemo ga mjesečno u Care i Guard paketu.','gauge'],['Nakon nevremena','Guard uključuje prioritetni pregled nakon jake kiše.','shield']],
    reportK: 'Nakon svakog dolaska', reportT: 'Ne morate nagađati što se događa u marini.', reportB: 'Dobivate fotografije i kratku poruku. Ako je sve u redu, to jasno kažemo. Ako nije, vidite što smo pronašli i što predlažemo.', reportExample: 'Primjer izvještaja', reportMeta: 'Redoviti obilazak · Marina Veruda', reportRows: [['Vez i bokobrani','U redu'],['Kaljuža','Suha'],['Akumulator','12,7 V'],['Pokrov i unutrašnjost','U redu']], reportNote: '4 fotografije priložene',
    plansK: 'Mjesečni paketi', plansT: 'Odaberite duljinu broda i usporedite cijene.', plansB: 'Sve cijene su mjesečne. Konačna ponuda može ovisiti o marini i stanju broda.', sizes: ['Do 8 m','8 do 12 m','Više od 12 m'], visits: ['1 obilazak mjesečno','2 obilaska mjesečno','4 obilaska mjesečno'],
    plans: [['Watch','Osnovni nadzor','Za brod kojem treba jedan temeljit pregled mjesečno.',['Vez i bokobrani','Kaljuža i akumulator','Vlaga i pokrov','Fotografije nakon obilaska']],['Care','Redovita briga','Za vlasnike koji žele češći nadzor i preventivne provjere.',['Sve iz Watch paketa','Pregled interijera i eksterijera','Obalno napajanje i ventilacija','Mjesečno pokretanje motora']],['Guard','Najviše pokrića','Za tjedne preglede i prioritet nakon nevremena.',['Sve iz Care paketa','Kontrola apsorbera vlage','Prioritet nakon oluje','Pregled nakon jake kiše']]], featured: 'Najčešći izbor', quote: 'Zatražite ponudu', monthly: 'mj.',
    addonsK: 'Dodatne usluge', addonsT: 'Treba pripremiti brod prije dolaska?', addonsNote: 'Dogovaraju se zasebno. Trošak namirnica nije uključen u uslugu opskrbe.', addons: [['Pranje broda','€50 do €80'],['Pre-arrival priprema','€60'],['Opskrba broda','€25 + trošak'],['Prva tura rublja','€50'],['Svaka dodatna tura','€20'],['Samostalno pokretanje motora','€35']],
    whyK: 'Tko brine o brodu', whyT: 'Filip je vaš kontakt u marini.', whyB: 'Ista osoba obilazi brod, vodi bilješke i javlja vam se. Tako se promjene lakše primijete, a vi ne morate svaki put objašnjavati povijest broda nekome novom.', values: [['Lokalno i osobno','Filip radi na području Pule, Verude, Bunarine i Medulina.'],['Kratko i jasno','Dobivate činjenice, fotografije i prijedlog sljedećeg koraka.'],['Bez radova na svoju ruku','Dodatni posao dogovaramo prije nego što ga napravimo.']],
    areaK: 'Područje rada', areaT: 'Pula, Veruda, Bunarina i Medulin.', areaB: 'Za drugu lokaciju u Istri pošaljite upit. Provjerit ćemo možemo li je uključiti u rutu.',
    faqT: 'Prije prvog obilaska', faq: [['Moram li biti u Puli?','Ne. Ako imamo pristup brodu i potrebne informacije, sve možemo dogovoriti na daljinu.'],['Što točno dobivam nakon obilaska?','Kratku poruku i fotografije. Ako uočimo problem, napisat ćemo što smo vidjeli i koji bi bio razuman sljedeći korak.'],['Radite li popravke bez odobrenja?','Ne. Prvo vas kontaktiramo. Dodatni rad i vanjski servis dogovaraju se prije izvedbe.'],['Mogu li naručiti samo jednu uslugu?','Da. Pranje, priprema prije dolaska, opskrba, rublje i samostalno pokretanje motora mogu se ugovoriti odvojeno.'],['Vrijede li cijene za sve brodove?','Cjenik je orijentacijski. Konačna cijena ovisi o duljini, marini i konkretnom stanju broda.']],
    ctaK: 'Prvi korak', ctaT: 'Pošaljite nam tri informacije.', ctaB: 'Napišite u kojoj je marini brod, koliko je dug i koliko često želite obilazak. Filip će vam predložiti paket.', whatsapp: 'Pošaljite WhatsApp poruku', call: 'Nazovite Filipa', footer: 'Nadzor i održavanje brodova u Puli i južnoj Istri.', legal: 'Pravni tekstovi su u pripremi. Prije objave treba unijeti podatke poslovnog subjekta.'
  },
  en: {
    nav: ['How it works', 'Plans', 'About', 'FAQ'], eyebrow: 'Boat care in Pula and southern Istria',
    hero: 'Someone checks your boat. Even when you are not here.', intro: 'Filip visits your boat, checks the agreed items and sends photos after every visit. You know what is happening without travelling to the marina.',
    primary: 'Arrange an initial check', secondary: 'View the plans', trust: ['Pula, Veruda, Bunarina and Medulin', 'Available all year', 'Photos after every visit'], status: 'Report sent to owner',
    problemK: 'While you are away', problemT: 'A boat does not stop changing just because it is moored.', problemB: 'Rain fills the bilge. Batteries lose charge. Lines loosen. Regular checks catch these changes while they are still straightforward to deal with.',
    processK: 'How it works', processT: 'You know when we visit, what we check and what we find.', steps: [['01','Initial check','We learn the boat, its berth and what matters to you.'],['02','Visit schedule','One, two or four visits each month, depending on the plan.'],['03','Checks and photos','After every visit, you get a short report in plain language.'],['04','Approval before work','If something needs attention, we contact you before adding any cost.']],
    checksK: 'The checklist', checksT: 'Every visit has a purpose.', checks: [['Bilge and water','We look for water and signs of a leak.','water'],['Moisture and cover','We check condensation, absorbers and the cover.','wind'],['Battery','We check its condition according to the plan.','battery'],['Lines and fenders','We inspect the mooring lines, fenders and boat position.','waves'],['Engine','Care and Guard include a monthly engine start.','gauge'],['After bad weather','Guard includes priority checks after heavy rain.','shield']],
    reportK: 'After every visit', reportT: 'No guessing what is happening at the marina.', reportB: 'You receive photos and a short message. If everything is fine, we say so. If it is not, you see what we found and what we suggest next.', reportExample: 'Sample report', reportMeta: 'Regular visit · Marina Veruda', reportRows: [['Lines and fenders','OK'],['Bilge','Dry'],['Battery','12.7 V'],['Cover and interior','OK']], reportNote: '4 photos attached',
    plansK: 'Monthly plans', plansT: 'Select your boat length and compare prices.', plansB: 'All prices are monthly. The final quote may vary by marina and the condition of the boat.', sizes: ['Up to 8 m','8 to 12 m','Over 12 m'], visits: ['1 visit per month','2 visits per month','4 visits per month'],
    plans: [['Watch','Essential oversight','One thorough monthly check for boats that need a regular eye on them.',['Lines and fenders','Bilge and battery','Moisture and cover','Photos after the visit']],['Care','Regular care','More frequent oversight and preventive checks.',['Everything in Watch','Interior and exterior check','Shore power and ventilation','Monthly engine start']],['Guard','Maximum coverage','Weekly checks and priority after bad weather.',['Everything in Care','Moisture absorber check','Storm priority','Check after heavy rain']]], featured: 'Most popular', quote: 'Request a quote', monthly: 'mo.',
    addonsK: 'Extra services', addonsT: 'Need the boat ready before you arrive?', addonsNote: 'Booked separately. Provisioning does not include the cost of groceries or supplies.', addons: [['Boat washing','€50 to €80'],['Pre-arrival preparation','€60'],['Provisioning assistance','€25 + cost'],['First laundry load','€50'],['Each additional load','€20'],['Standalone engine start','€35']],
    whyK: 'Who looks after the boat', whyT: 'Filip is your contact at the marina.', whyB: 'The same person checks the boat, keeps the notes and speaks with you. Changes are easier to spot, and you do not need to explain the boat to someone new each time.', values: [['Local and personal','Filip works in Pula, Veruda, Bunarina and Medulin.'],['Short, clear reports','You get facts, photos and a sensible next step.'],['No unapproved work','We agree on any additional work before it starts.']],
    areaK: 'Service area', areaT: 'Pula, Veruda, Bunarina and Medulin.', areaB: 'For another location in Istria, send an enquiry. We will check whether it can fit the route.',
    faqT: 'Before the first visit', faq: [['Do I need to be in Pula?','No. If we have access to the boat and the information we need, we can arrange everything remotely.'],['What do I get after a visit?','A short message and photos. If we find an issue, we explain what we saw and suggest a reasonable next step.'],['Do you carry out repairs without approval?','No. We contact you first. Any extra work or outside service is agreed before it starts.'],['Can I book a single service?','Yes. Washing, pre-arrival preparation, provisioning, laundry and a standalone engine start can be booked separately.'],['Does the price apply to every boat?','The price list is indicative. The final price depends on length, marina and the specific condition of the boat.']],
    ctaK: 'First step', ctaT: 'Send us three details.', ctaB: 'Tell us the marina, the boat length and how often you want it checked. Filip will suggest a plan.', whatsapp: 'Send a WhatsApp message', call: 'Call Filip', footer: 'Boat checks and maintenance in Pula and southern Istria.', legal: 'Legal copy is being prepared. Business details must be added before publication.'
  },
  de: {
    nav: ['So funktioniert es', 'Pakete', 'Über uns', 'FAQ'], eyebrow: 'Bootsbetreuung in Pula und Südistrien',
    hero: 'Jemand schaut nach Ihrem Boot. Auch wenn Sie nicht vor Ort sind.', intro: 'Filip kontrolliert Ihr Boot, prüft die vereinbarten Punkte und schickt nach jedem Besuch Fotos. So wissen Sie, was passiert, ohne selbst zur Marina fahren zu müssen.',
    primary: 'Erstkontrolle vereinbaren', secondary: 'Pakete ansehen', trust: ['Pula, Veruda, Bunarina und Medulin', 'Ganzjährig verfügbar', 'Fotos nach jedem Besuch'], status: 'Bericht an den Eigner gesendet',
    problemK: 'Während Sie weg sind', problemT: 'Ein Boot verändert sich auch dann, wenn es nur am Liegeplatz liegt.', problemB: 'Regen füllt die Bilge. Batterien verlieren Ladung. Leinen lockern sich. Regelmäßige Kontrollen zeigen solche Veränderungen, solange sie noch einfach zu beheben sind.',
    processK: 'So funktioniert es', processT: 'Sie wissen, wann wir kommen, was wir prüfen und was wir vorfinden.', steps: [['01','Erstkontrolle','Wir lernen das Boot, den Liegeplatz und Ihre Prioritäten kennen.'],['02','Fester Rhythmus','Ein, zwei oder vier Besuche pro Monat, je nach Paket.'],['03','Kontrolle und Fotos','Nach jedem Besuch erhalten Sie einen kurzen, verständlichen Bericht.'],['04','Freigabe vor Arbeiten','Wenn etwas zu tun ist, melden wir uns vor zusätzlichen Kosten.']],
    checksK: 'Die Checkliste', checksT: 'Jeder Besuch hat einen klaren Zweck.', checks: [['Bilge und Wasser','Wir achten auf Wasser und mögliche Undichtigkeiten.','water'],['Feuchtigkeit und Persenning','Wir prüfen Kondenswasser, Absorber und Abdeckung.','wind'],['Batterie','Wir prüfen den Zustand entsprechend dem Paket.','battery'],['Leinen und Fender','Wir kontrollieren Leinen, Fender und die Lage des Boots.','waves'],['Motor','Care und Guard enthalten einen monatlichen Motorstart.','gauge'],['Nach Unwetter','Guard enthält eine vorrangige Kontrolle nach starkem Regen.','shield']],
    reportK: 'Nach jedem Besuch', reportT: 'Sie müssen nicht raten, was in der Marina passiert.', reportB: 'Sie erhalten Fotos und eine kurze Nachricht. Ist alles in Ordnung, sagen wir das klar. Wenn nicht, sehen Sie, was wir gefunden haben und was wir als Nächstes empfehlen.', reportExample: 'Beispielbericht', reportMeta: 'Regelmäßige Kontrolle · Marina Veruda', reportRows: [['Leinen und Fender','In Ordnung'],['Bilge','Trocken'],['Batterie','12,7 V'],['Abdeckung und Innenraum','In Ordnung']], reportNote: '4 Fotos angehängt',
    plansK: 'Monatliche Pakete', plansT: 'Bootslänge wählen und Preise vergleichen.', plansB: 'Alle Preise gelten pro Monat. Das endgültige Angebot kann je nach Marina und Zustand des Boots abweichen.', sizes: ['Bis 8 m','8 bis 12 m','Über 12 m'], visits: ['1 Besuch pro Monat','2 Besuche pro Monat','4 Besuche pro Monat'],
    plans: [['Watch','Grundkontrolle','Eine gründliche monatliche Kontrolle für einen verlässlichen Überblick.',['Leinen und Fender','Bilge und Batterie','Feuchtigkeit und Abdeckung','Fotos nach dem Besuch']],['Care','Regelmäßige Betreuung','Häufigere Kontrollen und vorbeugende Checks.',['Alles aus Watch','Innen- und Außenkontrolle','Landstrom und Belüftung','Monatlicher Motorstart']],['Guard','Maximale Betreuung','Wöchentliche Kontrollen und Priorität nach Unwetter.',['Alles aus Care','Kontrolle der Feuchtigkeitsabsorber','Priorität nach Sturm','Kontrolle nach starkem Regen']]], featured: 'Beliebteste Wahl', quote: 'Angebot anfragen', monthly: 'Mon.',
    addonsK: 'Zusatzleistungen', addonsT: 'Soll das Boot vor Ihrer Ankunft bereit sein?', addonsNote: 'Separat buchbar. Die Kosten für Einkäufe sind bei der Versorgung nicht enthalten.', addons: [['Bootswäsche','€50 bis €80'],['Vorbereitung vor Ankunft','€60'],['Versorgung des Boots','€25 + Kosten'],['Erste Wäscheladung','€50'],['Jede weitere Ladung','€20'],['Einzelner Motorstart','€35']],
    whyK: 'Wer sich um Ihr Boot kümmert', whyT: 'Filip ist Ihr Ansprechpartner in der Marina.', whyB: 'Dieselbe Person kontrolliert das Boot, führt die Notizen und spricht mit Ihnen. Veränderungen fallen schneller auf, und Sie müssen nicht jedes Mal jemand Neuem das Boot erklären.', values: [['Vor Ort und persönlich','Filip arbeitet in Pula, Veruda, Bunarina und Medulin.'],['Kurze, klare Berichte','Sie erhalten Fakten, Fotos und einen sinnvollen nächsten Schritt.'],['Keine Arbeiten ohne Freigabe','Zusätzliche Arbeiten stimmen wir vorher mit Ihnen ab.']],
    areaK: 'Einsatzgebiet', areaT: 'Pula, Veruda, Bunarina und Medulin.', areaB: 'Für einen anderen Standort in Istrien senden Sie bitte eine Anfrage. Wir prüfen, ob er in unsere Route passt.',
    faqT: 'Vor dem ersten Besuch', faq: [['Muss ich in Pula sein?','Nein. Wenn wir Zugang zum Boot und die nötigen Informationen haben, können wir alles aus der Ferne organisieren.'],['Was erhalte ich nach einem Besuch?','Eine kurze Nachricht und Fotos. Bei einem Problem erklären wir, was wir gesehen haben und welcher nächste Schritt sinnvoll ist.'],['Führen Sie Reparaturen ohne Freigabe aus?','Nein. Wir melden uns zuerst. Zusätzliche Arbeiten oder externe Services werden vor Beginn abgestimmt.'],['Kann ich eine einzelne Leistung buchen?','Ja. Bootswäsche, Vorbereitung, Versorgung, Wäsche und ein einzelner Motorstart können separat gebucht werden.'],['Gilt der Preis für jedes Boot?','Die Preisliste ist ein Richtwert. Der Endpreis hängt von Länge, Marina und Zustand des Boots ab.']],
    ctaK: 'Der erste Schritt', ctaT: 'Schicken Sie uns drei Angaben.', ctaB: 'Nennen Sie Marina, Bootslänge und gewünschte Häufigkeit. Filip empfiehlt Ihnen das passende Paket.', whatsapp: 'WhatsApp-Nachricht senden', call: 'Filip anrufen', footer: 'Bootskontrolle und Wartung in Pula und Südistrien.', legal: 'Die Rechtstexte werden vorbereitet. Vor der Veröffentlichung müssen die Unternehmensdaten ergänzt werden.'
  }
};

const checkIcons = { water: Droplets, wind: Wind, battery: BatteryCharging, waves: Waves, gauge: Gauge, shield: ShieldCheck };
const sizeKeys: Size[] = ['small', 'medium', 'large'];

export default function Home() {
  const [lang, setLang] = useState<Lang>('en');
  const [size, setSize] = useState<Size>('small');
  const [menuOpen, setMenuOpen] = useState(false);
  const t = content[lang];
  const nav = [['#process', t.nav[0]], ['#plans', t.nav[1]], ['#about', t.nav[2]], ['#faq', t.nav[3]]];

  useEffect(() => { document.documentElement.lang = lang; }, [lang]);

  return <main>
    <header className="header">
      <a className="brand brandFull" href="#top" aria-label="Boat Care and Check"><img src="/brand/boat-care-logo-full.png" alt="Boat Care and Check"/></a>
      <nav className="nav">{nav.map(([href,label]) => <a key={href} href={href}>{label}</a>)}</nav>
      <div className="actions"><div className="lang" aria-label="Language">{(['hr','en','de'] as Lang[]).map((item,i) => <span key={item}><button className={lang === item ? 'on' : ''} onClick={() => setLang(item)}>{item.toUpperCase()}</button>{i < 2 && <i>/</i>}</span>)}</div><a className="mini" href="https://wa.me/385915033936">WhatsApp <ArrowRight size={14}/></a><button className="menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Menu">{menuOpen ? <X/> : <Menu/>}</button></div>
      {menuOpen && <nav className="mobile">{nav.map(([href,label]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav>}
    </header>

    <section className="hero photoHero textHero" id="top"><div className="heroContent"><p className="eyebrow"><span/>{t.eyebrow}</p><h1>{t.hero}</h1><p className="intro">{t.intro}</p><div className="heroBtns"><a className="button gold" href="https://wa.me/385915033936">{t.primary}<ArrowRight size={18}/></a><a className="textLink" href="#plans">{t.secondary}<ArrowDown size={17}/></a></div></div><div className="heroSignal" aria-hidden="true"><span>LOCAL</span><strong>01</strong><small>PULA · ISTRIA</small></div><div className="trust">{t.trust.map((x,i) => <div key={x}>{i === 0 ? <MapPin/> : i === 1 ? <ShieldCheck/> : <MessageCircle/>}<span>{x}</span></div>)}</div></section>

    <section className="section cream"><div className="split"><div><p className="kicker">{t.problemK}</p><h2>{t.problemT}</h2></div><p>{t.problemB}</p></div></section>

    <section className="section" id="process"><Heading kicker={t.processK} title={t.processT}/><div className="steps">{t.steps.map(([number,title,body],i) => <article key={number}><StepNumber number={number} side={i % 2 ? 'right' : 'left'}/><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <section className="section checks"><Heading kicker={t.checksK} title={t.checksT}/><div className="checkGrid">{t.checks.map(([title,body,icon]) => { const Icon = checkIcons[icon as keyof typeof checkIcons]; return <article key={title}><Icon/><div><h3>{title}</h3><p>{body}</p></div></article>; })}</div></section>

    <section className="reportSection"><div className="reportCopy"><p className="kicker light">{t.reportK}</p><h2>{t.reportT}</h2><p>{t.reportB}</p><div className="messagePreview"><i/><div><strong>Boat Care Pula</strong><span>{t.status}</span></div><Check/></div></div><div className="reportExample"><header><span>{t.reportExample}</span><b>BCP 024</b></header><p>{t.reportMeta}</p><div>{t.reportRows.map(([label,value]) => <p key={label}><span>{label}</span><strong><Check/>{value}</strong></p>)}</div><footer><MessageCircle/>{t.reportNote}</footer></div></section>

    <section className="section plans" id="plans"><Heading kicker={t.plansK} title={t.plansT} body={t.plansB} center/><div className="sizePicker" role="group" aria-label="Boat length">{sizeKeys.map((key,i) => <button key={key} className={size === key ? 'active' : ''} onClick={() => setSize(key)}>{t.sizes[i]}</button>)}</div><div className="planGrid">{t.plans.map((plan,i) => { const [name,label,desc,items] = plan; return <article className={i === 1 ? 'featured' : ''} key={name as string}>{i === 1 && <b className="badge">{t.featured}</b>}<p className="label">{label as string}</p><h3>{name as string}</h3><p className="visits">{t.visits[i]}</p><p className="price"><small>{lang === 'de' ? 'ab' : lang === 'hr' ? 'od' : 'from'}</small> €{prices[name as keyof typeof prices][size]} <span>/ {t.monthly}</span></p><p className="desc">{desc as string}</p><ul>{(items as string[]).map(item => <li key={item}><Check/>{item}</li>)}</ul><a href="https://wa.me/385915033936">{t.quote}<ArrowRight/></a></article>; })}</div><p className="size">* {t.plansB}</p></section>

    <section className="section addons"><div><p className="kicker">{t.addonsK}</p><h2>{t.addonsT}</h2><p>{t.addonsNote}</p></div><div className="addonList">{t.addons.map(([name,price],i) => <div key={name}><StepNumber number={`0${i+1}`} side={i % 2 ? 'right' : 'left'}/><strong>{name}</strong><b>{price}</b></div>)}</div></section>

    <section className="why" id="about"><div className="photo"><img src="/brand/filip-inspection.jpg" alt="Filip inspecting a boat in Pula"/></div><div className="whyCopy"><p className="kicker light">{t.whyK}</p><h2>{t.whyT}</h2><p>{t.whyB}</p><div className="values">{t.values.map(([title,body]) => <div key={title}><ShieldCheck/><span><strong>{title}</strong><small>{body}</small></span></div>)}</div></div></section>

    <section className="section area"><div><p className="kicker">{t.areaK}</p><h2>{t.areaT}</h2><p>{t.areaB}</p></div><figure className="areaPhoto"><img src="/brand/filip-checklist-wide.jpg" alt="Filip completing a boat inspection checklist"/><figcaption><MapPin/> Pula, Istria</figcaption></figure></section>

    <section className="section faq" id="faq"><Heading kicker="FAQ" title={t.faqT}/><div>{t.faq.map(([question,answer]) => <details key={question}><summary>{question}<ChevronDown/></summary><p>{answer}</p></details>)}</div></section>

    <section className="final"><div><p className="kicker light">{t.ctaK}</p><h2>{t.ctaT}</h2><p>{t.ctaB}</p></div><div className="ctaBtns"><a className="button gold" href="https://wa.me/385915033936"><MessageCircle/>{t.whatsapp}</a><a className="button outline" href="tel:+385915033936">{t.call}<span>+385 91 503 3936</span></a></div></section>

    <footer><div className="footMain"><a className="brand brandFull" href="#top" aria-label="Boat Care and Check"><img src="/brand/boat-care-logo-full.png" alt="Boat Care and Check"/></a><p>{t.footer}</p><div><a href="mailto:boatcarepula@gmail.com">boatcarepula@gmail.com</a><a href="tel:+385915033936">+385 91 503 3936</a><a href="https://instagram.com/boatcarepula">@boatcarepula</a></div></div><div className="footBottom"><span>© 2026 Boat Care Pula</span><nav><a href="#legal">Privacy</a><a href="#legal">Cookies</a><a href="#legal">Impressum</a></nav></div><p className="legal" id="legal">{t.legal}</p></footer>
    <a className="float" href="https://wa.me/385915033936" aria-label="WhatsApp"><MessageCircle/></a>
  </main>;
}

function Heading({kicker,title,body,center=false}:{kicker:string,title:string,body?:string,center?:boolean}) { return <div className={`heading ${center ? 'center' : ''}`}><p className="kicker">{kicker}</p><h2>{title}</h2>{body && <p>{body}</p>}</div>; }
function StepNumber({number,side}:{number:string,side:'left'|'right'}) { return <div className={`stepNumber ${side}`}><span/><strong>{number}</strong><span/></div>; }
