'use client';

import { useEffect, useState, type FormEvent } from 'react';
import { ArrowDown, ArrowRight, BatteryCharging, CalendarCheck, Check, ChevronDown, ClipboardList, Droplets, FileCheck2, Gauge, History, MapPin, Menu, MessageCircle, Send, ShieldCheck, ShoppingBag, Waves, Wind, X } from 'lucide-react';

type Lang = 'hr' | 'en' | 'de';
type Size = 'small' | 'medium' | 'large';

const prices = {
  Watch: { small: 80, medium: 100, large: 120 },
  Care: { small: 160, medium: 200, large: 240 },
  Guard: { small: 290, medium: 360, large: 430 },
};

const content = {
  hr: {
    nav: ['Kako radi', 'Paketi', 'O nama', 'FAQ'], eyebrow: 'Lokalna briga za vlasnike koji nisu stalno u Puli',
    hero: 'Vaš brod ostaje u Puli. Netko pouzdan brine o njemu.', intro: 'Filip obilazi brod, provjerava dogovorene stavke i javlja vam što je zatekao. Kad nešto treba riješiti, imate jednu lokalnu osobu koju možete nazvati.',
    primary: 'Recite Filipu gdje je brod', secondary: 'Pogledajte pakete', trust: ['Polesana, Pula, Veruda, Bunarina i Medulin', 'Dostupno cijele godine', 'Fotografije nakon obilaska'], status: 'Izvještaj poslan vlasniku',
    problemK: 'Dok ste daleko', problemT: 'Brod ne miruje samo zato što je vezan.', problemB: 'Kiša napuni kaljužu. Akumulator oslabi. Konop se olabavi. Redoviti pregled znači da takve promjene vidimo dok ih je još jednostavno riješiti.',
    processK: 'Kako servis radi', processT: 'Znate kada dolazimo, što gledamo i što smo zatekli.', steps: [['01','Prvi pregled','Upoznajemo brod, vez i ono što vam je važno.'],['02','Ritam obilazaka','Jedan, dva ili četiri dolaska mjesečno, ovisno o paketu.'],['03','Provjera i fotografije','Nakon svakog obilaska šaljemo kratak, razumljiv izvještaj.'],['04','Dogovor prije radova','Ako nešto treba riješiti, javljamo se prije dodatnog troška.']],
    checksK: 'Kontrolna lista', checksT: 'Svaki obilazak ima smisao.', checks: [['Kaljuža i voda','Gledamo ima li vode ili znakova prodora.','water'],['Vlaga i pokrov','Provjeravamo kondenzaciju, apsorbere i pokrov.','wind'],['Akumulator','Provjeravamo stanje prema dogovorenom paketu.','battery'],['Vez i bokobrani','Pregledavamo konope, bokobrane i položaj broda.','waves'],['Motor','Pokrećemo ga mjesečno u Care i Guard paketu.','gauge'],['Nakon nevremena','Guard uključuje prioritetni pregled nakon jake kiše.','shield']],
    reportK: 'Nakon svakog dolaska', reportT: 'Ne morate nagađati što se događa u marini.', reportB: 'Dobivate fotografije i kratku poruku. Ako je sve u redu, to jasno kažemo. Ako nije, vidite što smo pronašli i što predlažemo.', reportExample: 'Primjer izvještaja', reportMeta: 'Redoviti obilazak · Marina Veruda', reportRows: [['Vez i bokobrani','U redu'],['Kaljuža','Suha'],['Akumulator','12,7 V'],['Pokrov i unutrašnjost','U redu']], reportNote: '4 fotografije priložene',
    plansK: 'Mjesečni paketi', plansT: 'Odaberite duljinu broda i usporedite cijene.', plansB: 'Sve cijene su mjesečne. Konačna ponuda može ovisiti o marini i stanju broda.', sizes: ['Do 8 m','8 do 12 m','Više od 12 m'], visits: ['1 obilazak mjesečno','2 obilaska mjesečno','4 obilaska mjesečno'],
    plans: [['Watch','Osnovni nadzor','Za brod kojem treba jedan temeljit pregled mjesečno.',['Vez i bokobrani','Kaljuža i akumulator','Vlaga i pokrov','Fotografije nakon obilaska']],['Care','Redovita briga','Za vlasnike koji žele češći nadzor i preventivne provjere.',['Sve iz Watch paketa','Pregled interijera i eksterijera','Obalno napajanje i ventilacija','Mjesečno pokretanje motora']],['Guard','Najviše pokrića','Za tjedne preglede i prioritet nakon nevremena.',['Sve iz Care paketa','Kontrola apsorbera vlage','Prioritet nakon oluje','Pregled nakon jake kiše']]], featured: 'Najčešći izbor', quote: 'Zatražite ponudu', monthly: 'mj.',
    addonsK: 'Dodatne usluge', addonsT: 'Treba pripremiti brod prije dolaska?', addonsNote: 'Dogovaraju se zasebno. Trošak namirnica nije uključen u uslugu opskrbe.', addons: [['Pranje broda','€50 do €80'],['Pre-arrival priprema','€60'],['Opskrba broda','€25 + trošak'],['Prva tura rublja','€50'],['Svaka dodatna tura','€20'],['Samostalno pokretanje motora','€35']],
    whyK: 'Tko brine o brodu', whyT: 'Filip je vaš kontakt u marini.', whyB: 'Ista osoba obilazi brod, vodi bilješke i javlja vam se. Tako se promjene lakše primijete, a vi ne morate svaki put objašnjavati povijest broda nekome novom.', values: [['Lokalno i osobno','Filip radi na području Pule, Verude, Bunarine i Medulina.'],['Kratko i jasno','Dobivate činjenice, fotografije i prijedlog sljedećeg koraka.'],['Bez radova na svoju ruku','Dodatni posao dogovaramo prije nego što ga napravimo.']],
    areaK: 'Područje rada', areaT: 'Polesana, Pula, Veruda, Bunarina i Medulin.', areaB: 'Za drugu lokaciju u Istri pošaljite upit. Provjerit ćemo možemo li je uključiti u rutu.',
    faqT: 'Prije prvog obilaska', faq: [['Moram li biti u Puli?','Ne. Ako imamo pristup brodu i potrebne informacije, sve možemo dogovoriti na daljinu.'],['Što točno dobivam nakon obilaska?','Kratku poruku i fotografije. Ako uočimo problem, napisat ćemo što smo vidjeli i koji bi bio razuman sljedeći korak.'],['Radite li popravke bez odobrenja?','Ne. Prvo vas kontaktiramo. Dodatni rad i vanjski servis dogovaraju se prije izvedbe.'],['Mogu li naručiti samo jednu uslugu?','Da. Pranje, priprema prije dolaska, opskrba, rublje i samostalno pokretanje motora mogu se ugovoriti odvojeno.'],['Vrijede li cijene za sve brodove?','Cjenik je orijentacijski. Konačna cijena ovisi o duljini, marini i konkretnom stanju broda.']],
    ctaK: 'Prvi korak', ctaT: 'Pošaljite nam tri informacije.', ctaB: 'Napišite u kojoj je marini brod, koliko je dug i koliko često želite obilazak. Filip će vam predložiti paket.', whatsapp: 'Pošaljite WhatsApp poruku', call: 'Nazovite Filipa', footer: 'Nadzor i održavanje brodova u Puli i južnoj Istri.', legal: 'Pravni tekstovi su u pripremi. Prije objave treba unijeti podatke poslovnog subjekta.'
  },
  en: {
    nav: ['How it works', 'Plans', 'About', 'FAQ'], eyebrow: 'Local care for owners who are not always in Pula',
    hero: 'Your boat stays in Pula. Someone reliable looks after it.', intro: 'Filip checks the boat, follows the agreed list and tells you what he found. When something needs sorting, you have one local person to call.',
    primary: 'Tell Filip where your boat is', secondary: 'View the plans', trust: ['Polesana, Pula, Veruda, Bunarina and Medulin', 'Available all year', 'Photos after every visit'], status: 'Report sent to owner',
    problemK: 'While you are away', problemT: 'A boat does not stop changing just because it is moored.', problemB: 'Rain fills the bilge. Batteries lose charge. Lines loosen. Regular checks catch these changes while they are still straightforward to deal with.',
    processK: 'How it works', processT: 'You know when we visit, what we check and what we find.', steps: [['01','Initial check','We learn the boat, its berth and what matters to you.'],['02','Visit schedule','One, two or four visits each month, depending on the plan.'],['03','Checks and photos','After every visit, you get a short report in plain language.'],['04','Approval before work','If something needs attention, we contact you before adding any cost.']],
    checksK: 'The checklist', checksT: 'Every visit has a purpose.', checks: [['Bilge and water','We look for water and signs of a leak.','water'],['Moisture and cover','We check condensation, absorbers and the cover.','wind'],['Battery','We check its condition according to the plan.','battery'],['Lines and fenders','We inspect the mooring lines, fenders and boat position.','waves'],['Engine','Care and Guard include a monthly engine start.','gauge'],['After bad weather','Guard includes priority checks after heavy rain.','shield']],
    reportK: 'After every visit', reportT: 'No guessing what is happening at the marina.', reportB: 'You receive photos and a short message. If everything is fine, we say so. If it is not, you see what we found and what we suggest next.', reportExample: 'Sample report', reportMeta: 'Regular visit · Marina Veruda', reportRows: [['Lines and fenders','OK'],['Bilge','Dry'],['Battery','12.7 V'],['Cover and interior','OK']], reportNote: '4 photos attached',
    plansK: 'Monthly plans', plansT: 'Select your boat length and compare prices.', plansB: 'All prices are monthly. The final quote may vary by marina and the condition of the boat.', sizes: ['Up to 8 m','8 to 12 m','Over 12 m'], visits: ['1 visit per month','2 visits per month','4 visits per month'],
    plans: [['Watch','Essential oversight','One thorough monthly check for boats that need a regular eye on them.',['Lines and fenders','Bilge and battery','Moisture and cover','Photos after the visit']],['Care','Regular care','More frequent oversight and preventive checks.',['Everything in Watch','Interior and exterior check','Shore power and ventilation','Monthly engine start']],['Guard','Maximum coverage','Weekly checks and priority after bad weather.',['Everything in Care','Moisture absorber check','Storm priority','Check after heavy rain']]], featured: 'Most popular', quote: 'Request a quote', monthly: 'mo.',
    addonsK: 'Extra services', addonsT: 'Need the boat ready before you arrive?', addonsNote: 'Booked separately. Provisioning does not include the cost of groceries or supplies.', addons: [['Boat washing','€50 to €80'],['Pre-arrival preparation','€60'],['Provisioning assistance','€25 + cost'],['First laundry load','€50'],['Each additional load','€20'],['Standalone engine start','€35']],
    whyK: 'Who looks after the boat', whyT: 'Filip is your contact at the marina.', whyB: 'The same person checks the boat, keeps the notes and speaks with you. Changes are easier to spot, and you do not need to explain the boat to someone new each time.', values: [['Local and personal','Filip works in Pula, Veruda, Bunarina and Medulin.'],['Short, clear reports','You get facts, photos and a sensible next step.'],['No unapproved work','We agree on any additional work before it starts.']],
    areaK: 'Service area', areaT: 'Polesana, Pula, Veruda, Bunarina and Medulin.', areaB: 'For another location in Istria, send an enquiry. We will check whether it can fit the route.',
    faqT: 'Before the first visit', faq: [['Do I need to be in Pula?','No. If we have access to the boat and the information we need, we can arrange everything remotely.'],['What do I get after a visit?','A short message and photos. If we find an issue, we explain what we saw and suggest a reasonable next step.'],['Do you carry out repairs without approval?','No. We contact you first. Any extra work or outside service is agreed before it starts.'],['Can I book a single service?','Yes. Washing, pre-arrival preparation, provisioning, laundry and a standalone engine start can be booked separately.'],['Does the price apply to every boat?','The price list is indicative. The final price depends on length, marina and the specific condition of the boat.']],
    ctaK: 'First step', ctaT: 'Send us three details.', ctaB: 'Tell us the marina, the boat length and how often you want it checked. Filip will suggest a plan.', whatsapp: 'Send a WhatsApp message', call: 'Call Filip', footer: 'Boat checks and maintenance in Pula and southern Istria.', legal: 'Legal copy is being prepared. Business details must be added before publication.'
  },
  de: {
    nav: ['So funktioniert es', 'Pakete', 'Über uns', 'FAQ'], eyebrow: 'Betreuung vor Ort für Eigner, die nicht immer in Pula sind',
    hero: 'Ihr Boot bleibt in Pula. Jemand Zuverlässiges kümmert sich darum.', intro: 'Filip kontrolliert das Boot, arbeitet die vereinbarte Liste ab und meldet, was er vorgefunden hat. Wenn etwas zu erledigen ist, haben Sie einen Ansprechpartner vor Ort.',
    primary: 'Filip den Liegeplatz mitteilen', secondary: 'Pakete ansehen', trust: ['Polesana, Pula, Veruda, Bunarina und Medulin', 'Ganzjährig verfügbar', 'Fotos nach jedem Besuch'], status: 'Bericht an den Eigner gesendet',
    problemK: 'Während Sie weg sind', problemT: 'Ein Boot verändert sich auch dann, wenn es nur am Liegeplatz liegt.', problemB: 'Regen füllt die Bilge. Batterien verlieren Ladung. Leinen lockern sich. Regelmäßige Kontrollen zeigen solche Veränderungen, solange sie noch einfach zu beheben sind.',
    processK: 'So funktioniert es', processT: 'Sie wissen, wann wir kommen, was wir prüfen und was wir vorfinden.', steps: [['01','Erstkontrolle','Wir lernen das Boot, den Liegeplatz und Ihre Prioritäten kennen.'],['02','Fester Rhythmus','Ein, zwei oder vier Besuche pro Monat, je nach Paket.'],['03','Kontrolle und Fotos','Nach jedem Besuch erhalten Sie einen kurzen, verständlichen Bericht.'],['04','Freigabe vor Arbeiten','Wenn etwas zu tun ist, melden wir uns vor zusätzlichen Kosten.']],
    checksK: 'Die Checkliste', checksT: 'Jeder Besuch hat einen klaren Zweck.', checks: [['Bilge und Wasser','Wir achten auf Wasser und mögliche Undichtigkeiten.','water'],['Feuchtigkeit und Persenning','Wir prüfen Kondenswasser, Absorber und Abdeckung.','wind'],['Batterie','Wir prüfen den Zustand entsprechend dem Paket.','battery'],['Leinen und Fender','Wir kontrollieren Leinen, Fender und die Lage des Boots.','waves'],['Motor','Care und Guard enthalten einen monatlichen Motorstart.','gauge'],['Nach Unwetter','Guard enthält eine vorrangige Kontrolle nach starkem Regen.','shield']],
    reportK: 'Nach jedem Besuch', reportT: 'Sie müssen nicht raten, was in der Marina passiert.', reportB: 'Sie erhalten Fotos und eine kurze Nachricht. Ist alles in Ordnung, sagen wir das klar. Wenn nicht, sehen Sie, was wir gefunden haben und was wir als Nächstes empfehlen.', reportExample: 'Beispielbericht', reportMeta: 'Regelmäßige Kontrolle · Marina Veruda', reportRows: [['Leinen und Fender','In Ordnung'],['Bilge','Trocken'],['Batterie','12,7 V'],['Abdeckung und Innenraum','In Ordnung']], reportNote: '4 Fotos angehängt',
    plansK: 'Monatliche Pakete', plansT: 'Bootslänge wählen und Preise vergleichen.', plansB: 'Alle Preise gelten pro Monat. Das endgültige Angebot kann je nach Marina und Zustand des Boots abweichen.', sizes: ['Bis 8 m','8 bis 12 m','Über 12 m'], visits: ['1 Besuch pro Monat','2 Besuche pro Monat','4 Besuche pro Monat'],
    plans: [['Watch','Grundkontrolle','Eine gründliche monatliche Kontrolle für einen verlässlichen Überblick.',['Leinen und Fender','Bilge und Batterie','Feuchtigkeit und Abdeckung','Fotos nach dem Besuch']],['Care','Regelmäßige Betreuung','Häufigere Kontrollen und vorbeugende Checks.',['Alles aus Watch','Innen- und Außenkontrolle','Landstrom und Belüftung','Monatlicher Motorstart']],['Guard','Maximale Betreuung','Wöchentliche Kontrollen und Priorität nach Unwetter.',['Alles aus Care','Kontrolle der Feuchtigkeitsabsorber','Priorität nach Sturm','Kontrolle nach starkem Regen']]], featured: 'Beliebteste Wahl', quote: 'Angebot anfragen', monthly: 'Mon.',
    addonsK: 'Zusatzleistungen', addonsT: 'Soll das Boot vor Ihrer Ankunft bereit sein?', addonsNote: 'Separat buchbar. Die Kosten für Einkäufe sind bei der Versorgung nicht enthalten.', addons: [['Bootswäsche','€50 bis €80'],['Vorbereitung vor Ankunft','€60'],['Versorgung des Boots','€25 + Kosten'],['Erste Wäscheladung','€50'],['Jede weitere Ladung','€20'],['Einzelner Motorstart','€35']],
    whyK: 'Wer sich um Ihr Boot kümmert', whyT: 'Filip ist Ihr Ansprechpartner in der Marina.', whyB: 'Dieselbe Person kontrolliert das Boot, führt die Notizen und spricht mit Ihnen. Veränderungen fallen schneller auf, und Sie müssen nicht jedes Mal jemand Neuem das Boot erklären.', values: [['Vor Ort und persönlich','Filip arbeitet in Pula, Veruda, Bunarina und Medulin.'],['Kurze, klare Berichte','Sie erhalten Fakten, Fotos und einen sinnvollen nächsten Schritt.'],['Keine Arbeiten ohne Freigabe','Zusätzliche Arbeiten stimmen wir vorher mit Ihnen ab.']],
    areaK: 'Einsatzgebiet', areaT: 'Polesana, Pula, Veruda, Bunarina und Medulin.', areaB: 'Für einen anderen Standort in Istrien senden Sie bitte eine Anfrage. Wir prüfen, ob er in unsere Route passt.',
    faqT: 'Vor dem ersten Besuch', faq: [['Muss ich in Pula sein?','Nein. Wenn wir Zugang zum Boot und die nötigen Informationen haben, können wir alles aus der Ferne organisieren.'],['Was erhalte ich nach einem Besuch?','Eine kurze Nachricht und Fotos. Bei einem Problem erklären wir, was wir gesehen haben und welcher nächste Schritt sinnvoll ist.'],['Führen Sie Reparaturen ohne Freigabe aus?','Nein. Wir melden uns zuerst. Zusätzliche Arbeiten oder externe Services werden vor Beginn abgestimmt.'],['Kann ich eine einzelne Leistung buchen?','Ja. Bootswäsche, Vorbereitung, Versorgung, Wäsche und ein einzelner Motorstart können separat gebucht werden.'],['Gilt der Preis für jedes Boot?','Die Preisliste ist ein Richtwert. Der Endpreis hängt von Länge, Marina und Zustand des Boots ab.']],
    ctaK: 'Der erste Schritt', ctaT: 'Schicken Sie uns drei Angaben.', ctaB: 'Nennen Sie Marina, Bootslänge und gewünschte Häufigkeit. Filip empfiehlt Ihnen das passende Paket.', whatsapp: 'WhatsApp-Nachricht senden', call: 'Filip anrufen', footer: 'Bootskontrolle und Wartung in Pula und Südistrien.', legal: 'Die Rechtstexte werden vorbereitet. Vor der Veröffentlichung müssen die Unternehmensdaten ergänzt werden.'
  }
};

const checkIcons = { water: Droplets, wind: Wind, battery: BatteryCharging, waves: Waves, gauge: Gauge, shield: ShieldCheck };
const sizeKeys: Size[] = ['small', 'medium', 'large'];

const toolContent = {
  hr: {
    kicker: 'Digitalna briga', title: 'Manje dopisivanja. Više riješenih stvari.', body: 'Pošaljite podatke o brodu, naručite pripremu dolaska ili pregledajte kako izgleda uredna evidencija obilazaka.',
    tabs: ['Prvi upit','Primjer izvještaja','Pre-arrival','Odobrenje rada','Servisna povijest'],
    inquiryTitle: 'Recite nam gdje je brod i što vam treba.', marina: 'Marina', marinas: ['Marina Polesana','Pula','Veruda','Bunarina','Medulin','Druga lokacija'], length: 'Duljina broda', rhythm: 'Željeni ritam', rhythms: ['Jednom mjesečno','Dvaput mjesečno','Jednom tjedno','Nisam siguran'], arrival: 'Sljedeći dolazak u Pulu', note: 'Što vam je posebno važno?', send: 'Pošaljite upit putem WhatsAppa', optional: 'Nije obavezno',
    reportTitle: 'Primjer izvještaja nakon obilaska', sample: 'DEMO PRIKAZ', reportMeta: 'Marina Polesana · vez B24 · 09:42', reportRows: [['Vez i bokobrani','U redu'],['Kaljuža','Suha'],['Akumulator','12,7 V'],['Pokrov i unutrašnjost','U redu'],['Fotografije','4 priložene']], reportInfo: 'Kliknite stavku za detalj.', reportDetails: ['Konopi su pravilno zategnuti. Bokobrani su na mjestu.','Nema vidljive vode ni znakova prodora.','Napon zabilježen pri obilasku.','Pokrov je pričvršćen. Kabina je bez vidljive vlage.','Fotografirani su vez, kokpit, kaljuža i stanje akumulatora.'],
    arrivalTitle: 'Što treba biti spremno prije vašeg dolaska?', arrivalDate: 'Datum dolaska', arrivalItems: ['Provjetriti i pripremiti kabinu','Uključiti hladnjak','Nabaviti namirnice prema popisu','Dostaviti čistu posteljinu i ručnike','Oprati brod','Provjeriti akumulator','Preuzeti ili dostaviti rublje'], shopping: 'Popis za kupnju ili dodatna napomena', request: 'Pošaljite pre-arrival zahtjev',
    approvalTitle: 'Dodatni rad se ne izvodi bez vašeg odobrenja.', estimate: 'Primjer prijedloga', issue: 'Prednji desni bokobran treba zamijeniti.', price: 'Procijenjeni trošak: €45', approve: 'Odobravam putem WhatsAppa', discuss: 'Želim prvo razgovarati',
    historyTitle: 'Sve što se događalo s brodom, na jednom mjestu.', historyNote: 'Primjer servisne povijesti', history: [['28. kol','Redoviti obilazak','Sve u redu · 4 fotografije'],['16. kol','Pre-arrival priprema','Kabina provjetrena · hladnjak uključen'],['03. kol','Pregled nakon kiše','Kaljuža suha · pokrov pričvršćen'],['21. srp','Pranje broda','Usluga završena i fotografirana']]
  },
  en: {
    kicker: 'Digital boat care', title: 'Less back and forth. More things handled.', body: 'Send the boat details, request arrival preparation or see what a clear service record looks like.',
    tabs: ['First enquiry','Sample report','Pre-arrival','Approve work','Service history'],
    inquiryTitle: 'Tell us where the boat is and what you need.', marina: 'Marina', marinas: ['Marina Polesana','Pula','Veruda','Bunarina','Medulin','Another location'], length: 'Boat length', rhythm: 'Preferred schedule', rhythms: ['Once a month','Twice a month','Once a week','Not sure yet'], arrival: 'Next arrival in Pula', note: 'Anything we should pay special attention to?', send: 'Send the enquiry on WhatsApp', optional: 'Optional',
    reportTitle: 'Sample report after a visit', sample: 'DEMO VIEW', reportMeta: 'Marina Polesana · berth B24 · 09:42', reportRows: [['Lines and fenders','OK'],['Bilge','Dry'],['Battery','12.7 V'],['Cover and interior','OK'],['Photos','4 attached']], reportInfo: 'Select an item for details.', reportDetails: ['Lines are correctly tensioned. Fenders are in place.','No visible water or signs of ingress.','Voltage recorded during the visit.','The cover is secure. No visible moisture in the cabin.','Photos show the berth, cockpit, bilge and battery reading.'],
    arrivalTitle: 'What should be ready before you arrive?', arrivalDate: 'Arrival date', arrivalItems: ['Air and prepare the cabin','Switch on the fridge','Buy groceries from my list','Deliver clean bedding and towels','Wash the boat','Check the battery','Collect or deliver laundry'], shopping: 'Shopping list or an extra note', request: 'Send the pre-arrival request',
    approvalTitle: 'No extra work starts without your approval.', estimate: 'Sample proposal', issue: 'The forward starboard fender needs replacing.', price: 'Estimated cost: €45', approve: 'Approve on WhatsApp', discuss: 'Talk to Filip first',
    historyTitle: 'Everything that happened to the boat, in one place.', historyNote: 'Sample service history', history: [['28 Aug','Regular visit','All OK · 4 photos'],['16 Aug','Pre-arrival preparation','Cabin aired · fridge switched on'],['03 Aug','Check after rain','Bilge dry · cover secure'],['21 Jul','Boat wash','Service completed and photographed']]
  },
  de: {
    kicker: 'Digitale Betreuung', title: 'Weniger Nachrichten. Mehr erledigte Aufgaben.', body: 'Senden Sie die Bootsdaten, bestellen Sie die Vorbereitung Ihrer Ankunft oder sehen Sie, wie eine klare Servicehistorie aussieht.',
    tabs: ['Erste Anfrage','Beispielbericht','Vor Ankunft','Arbeit freigeben','Servicehistorie'],
    inquiryTitle: 'Sagen Sie uns, wo das Boot liegt und was Sie brauchen.', marina: 'Marina', marinas: ['Marina Polesana','Pula','Veruda','Bunarina','Medulin','Anderer Standort'], length: 'Bootslänge', rhythm: 'Gewünschter Rhythmus', rhythms: ['Einmal im Monat','Zweimal im Monat','Einmal pro Woche','Noch nicht sicher'], arrival: 'Nächste Ankunft in Pula', note: 'Worauf sollen wir besonders achten?', send: 'Anfrage per WhatsApp senden', optional: 'Optional',
    reportTitle: 'Beispielbericht nach einem Besuch', sample: 'DEMOANSICHT', reportMeta: 'Marina Polesana · Liegeplatz B24 · 09:42', reportRows: [['Leinen und Fender','In Ordnung'],['Bilge','Trocken'],['Batterie','12,7 V'],['Abdeckung und Innenraum','In Ordnung'],['Fotos','4 angehängt']], reportInfo: 'Wählen Sie einen Punkt für Details.', reportDetails: ['Leinen sind richtig gespannt. Die Fender sind an ihrem Platz.','Kein sichtbares Wasser und keine Anzeichen für Wassereintritt.','Spannung beim Besuch dokumentiert.','Die Abdeckung ist befestigt. Keine sichtbare Feuchtigkeit in der Kabine.','Fotos zeigen Liegeplatz, Cockpit, Bilge und Batteriewert.'],
    arrivalTitle: 'Was soll vor Ihrer Ankunft vorbereitet sein?', arrivalDate: 'Ankunftsdatum', arrivalItems: ['Kabine lüften und vorbereiten','Kühlschrank einschalten','Lebensmittel nach Liste einkaufen','Saubere Bettwäsche und Handtücher bringen','Boot waschen','Batterie prüfen','Wäsche abholen oder liefern'], shopping: 'Einkaufsliste oder zusätzliche Nachricht', request: 'Anfrage vor Ankunft senden',
    approvalTitle: 'Zusätzliche Arbeiten beginnen erst nach Ihrer Freigabe.', estimate: 'Beispielvorschlag', issue: 'Der vordere Fender an Steuerbord muss ersetzt werden.', price: 'Geschätzte Kosten: €45', approve: 'Per WhatsApp freigeben', discuss: 'Zuerst mit Filip sprechen',
    historyTitle: 'Alles rund um das Boot an einem Ort.', historyNote: 'Beispiel einer Servicehistorie', history: [['28. Aug','Regelmäßige Kontrolle','Alles in Ordnung · 4 Fotos'],['16. Aug','Vorbereitung vor Ankunft','Kabine gelüftet · Kühlschrank eingeschaltet'],['03. Aug','Kontrolle nach Regen','Bilge trocken · Abdeckung befestigt'],['21. Juli','Bootswäsche','Service erledigt und fotografiert']]
  }
};

const conciergeContent = {
  hr: { kicker: 'Polesana concierge', title: 'Stvari koje ne trebate rješavati iz druge države.', body: 'Filip može preuzeti praktične zadatke prije dolaska, nakon odlaska ili dok je brod na vezu.', items: ['Nabava namirnica prema popisu','Pranje i dostava rublja','Zamjena posteljine i ručnika','Priprema broda prije dolaska','Zatvaranje broda nakon odlaska','Preuzimanje paketa za brod','Koordinacija lokalnog servisera','Prisutnost tijekom dolaska majstora','Fotografiranje obavljenih radova','Pregled nakon oluje ili jake kiše','Provjera prije dužeg putovanja vlasnika','Sezonsko otvaranje i zatvaranje broda','Vođenje popisa potrošnog materijala','Podsjetnici za registraciju, servis i osiguranje'] },
  en: { kicker: 'Polesana concierge', title: 'Practical jobs you should not have to manage from another country.', body: 'Filip can handle useful tasks before you arrive, after you leave or while the boat stays at its berth.', items: ['Groceries bought from your list','Laundry collection and delivery','Fresh bedding and towel change','Boat preparation before arrival','Closing the boat after departure','Receiving parcels for the boat','Coordinating a local service provider','Being present when a technician visits','Photographing completed work','Checks after a storm or heavy rain','A check before the owner is away for longer','Seasonal opening and closing','Keeping track of consumable supplies','Reminders for registration, service and insurance'] },
  de: { kicker: 'Polesana Concierge', title: 'Praktische Aufgaben, die Sie nicht aus dem Ausland organisieren müssen.', body: 'Filip übernimmt Aufgaben vor Ihrer Ankunft, nach Ihrer Abreise oder während das Boot am Liegeplatz bleibt.', items: ['Einkauf nach Ihrer Liste','Wäsche abholen und liefern','Bettwäsche und Handtücher wechseln','Boot vor der Ankunft vorbereiten','Boot nach der Abreise schließen','Pakete für das Boot annehmen','Lokalen Servicebetrieb koordinieren','Beim Besuch eines Technikers anwesend sein','Erledigte Arbeiten fotografieren','Kontrolle nach Sturm oder starkem Regen','Kontrolle vor längerer Abwesenheit','Saisonale Öffnung und Schließung','Verbrauchsmaterial im Blick behalten','Erinnerungen für Registrierung, Service und Versicherung'] }
};

export default function Home() {
  const [lang, setLang] = useState<Lang>('en');
  const [size, setSize] = useState<Size>('small');
  const [menuOpen, setMenuOpen] = useState(false);
  const t = content[lang];
  const nav = [['#process', t.nav[0]], ['#plans', t.nav[1]], ['#about', t.nav[2]], ['#faq', t.nav[3]]];

  useEffect(() => { document.documentElement.lang = lang; }, [lang]);

  return <main>
    <header className="header">
      <a className="brand brandFull" href="#top" aria-label="Boat Care and Check"><img src="/brand/boat-care-logo-full.png" alt="Boat Care and Check"/></a>
      <nav className="nav">{nav.map(([href,label]) => <a key={href} href={href}>{label}</a>)}</nav>
      <div className="actions"><div className="lang" aria-label="Language">{(['hr','en','de'] as Lang[]).map((item,i) => <span key={item}><button className={lang === item ? 'on' : ''} onClick={() => setLang(item)}>{item.toUpperCase()}</button>{i < 2 && <i>/</i>}</span>)}</div><a className="mini" href="https://wa.me/385915033936">WhatsApp <ArrowRight size={14}/></a><button className="menu" onClick={() => setMenuOpen(!menuOpen)} aria-label="Menu">{menuOpen ? <X/> : <Menu/>}</button></div>
      {menuOpen && <nav className="mobile">{nav.map(([href,label]) => <a key={href} href={href} onClick={() => setMenuOpen(false)}>{label}</a>)}</nav>}
    </header>

    <section className="hero photoHero textHero" id="top"><div className="heroContent"><p className="eyebrow"><span/>{t.eyebrow}</p><h1>{t.hero}</h1><p className="intro">{t.intro}</p><div className="heroBtns"><a className="button gold" href="https://wa.me/385915033936">{t.primary}<ArrowRight size={18}/></a><a className="textLink" href="#plans">{t.secondary}<ArrowDown size={17}/></a></div></div><div className="trust">{t.trust.map((x,i) => <div key={x}>{i === 0 ? <MapPin/> : i === 1 ? <ShieldCheck/> : <MessageCircle/>}<span>{x}</span></div>)}</div></section>

    <section className="section cream"><div className="split"><div><p className="kicker">{t.problemK}</p><h2>{t.problemT}</h2></div><p>{t.problemB}</p></div></section>

    <section className="section" id="process"><Heading kicker={t.processK} title={t.processT}/><div className="steps">{t.steps.map(([number,title,body],i) => <article key={number}><StepNumber number={number} side={i % 2 ? 'right' : 'left'}/><h3>{title}</h3><p>{body}</p></article>)}</div></section>

    <section className="section checks"><Heading kicker={t.checksK} title={t.checksT}/><div className="checkGrid">{t.checks.map(([title,body,icon]) => { const Icon = checkIcons[icon as keyof typeof checkIcons]; return <article key={title}><Icon/><div><h3>{title}</h3><p>{body}</p></div></article>; })}</div></section>

    <section className="reportSection"><div className="reportCopy"><p className="kicker light">{t.reportK}</p><h2>{t.reportT}</h2><p>{t.reportB}</p><div className="messagePreview"><i/><div><strong>Boat Care Pula</strong><span>{t.status}</span></div><Check/></div></div><div className="reportExample"><header><span>{t.reportExample}</span><b>BCP 024</b></header><p>{t.reportMeta}</p><div>{t.reportRows.map(([label,value]) => <p key={label}><span>{label}</span><strong><Check/>{value}</strong></p>)}</div><footer><MessageCircle/>{t.reportNote}</footer></div></section>

    <section className="section plans" id="plans"><Heading kicker={t.plansK} title={t.plansT} body={t.plansB} center/><div className="sizePicker" role="group" aria-label="Boat length">{sizeKeys.map((key,i) => <button key={key} className={size === key ? 'active' : ''} onClick={() => setSize(key)}>{t.sizes[i]}</button>)}</div><div className="planGrid">{t.plans.map((plan,i) => { const [name,label,desc,items] = plan; return <article className={i === 1 ? 'featured' : ''} key={name as string}>{i === 1 && <b className="badge">{t.featured}</b>}<p className="label">{label as string}</p><h3>{name as string}</h3><p className="visits">{t.visits[i]}</p><p className="price"><small>{lang === 'de' ? 'ab' : lang === 'hr' ? 'od' : 'from'}</small> €{prices[name as keyof typeof prices][size]} <span>/ {t.monthly}</span></p><p className="desc">{desc as string}</p><ul>{(items as string[]).map(item => <li key={item}><Check/>{item}</li>)}</ul><a href="https://wa.me/385915033936">{t.quote}<ArrowRight/></a></article>; })}</div><p className="size">* {t.plansB}</p></section>

    <section className="section addons"><div><p className="kicker">{t.addonsK}</p><h2>{t.addonsT}</h2><p>{t.addonsNote}</p></div><div className="addonList">{t.addons.map(([name,price],i) => <div key={name}><StepNumber number={`0${i+1}`} side={i % 2 ? 'right' : 'left'}/><strong>{name}</strong><b>{price}</b></div>)}</div></section>

    <Concierge lang={lang}/>

    <section className="why" id="about"><div className="photo"><img src="/brand/filip-inspection.jpg" alt="Filip inspecting a boat in Pula"/></div><div className="whyCopy"><p className="kicker light">{t.whyK}</p><h2>{t.whyT}</h2><p>{t.whyB}</p><div className="values">{t.values.map(([title,body]) => <div key={title}><ShieldCheck/><span><strong>{title}</strong><small>{body}</small></span></div>)}</div></div></section>

    <section className="section area"><div><p className="kicker">{t.areaK}</p><h2>{t.areaT}</h2><p>{t.areaB}</p></div><figure className="areaPhoto"><img src="/brand/filip-checklist-wide.jpg" alt="Filip completing a boat inspection checklist"/><figcaption><MapPin/> Pula, Istria</figcaption></figure></section>

    <ClientTools lang={lang}/>

    <section className="section faq" id="faq"><Heading kicker="FAQ" title={t.faqT}/><div>{t.faq.map(([question,answer]) => <details key={question}><summary>{question}<ChevronDown/></summary><p>{answer}</p></details>)}</div></section>

    <section className="final"><div><p className="kicker light">{t.ctaK}</p><h2>{t.ctaT}</h2><p>{t.ctaB}</p></div><div className="ctaBtns"><a className="button gold" href="https://wa.me/385915033936"><MessageCircle/>{t.whatsapp}</a><a className="button outline" href="tel:+385915033936">{t.call}<span>+385 91 503 3936</span></a></div></section>

    <footer><div className="footMain"><a className="brand brandFull" href="#top" aria-label="Boat Care and Check"><img src="/brand/boat-care-logo-full.png" alt="Boat Care and Check"/></a><p>{t.footer}</p><div><a href="mailto:boatcarepula@gmail.com">boatcarepula@gmail.com</a><a href="tel:+385915033936">+385 91 503 3936</a><a href="https://instagram.com/boatcarepula">@boatcarepula</a></div></div><div className="footBottom"><span>© 2026 Boat Care Pula</span><nav><a href="#legal">Privacy</a><a href="#legal">Cookies</a><a href="#legal">Impressum</a></nav></div></footer>
    <a className="float" href="https://wa.me/385915033936" aria-label="WhatsApp"><MessageCircle/></a>
  </main>;
}

function Heading({kicker,title,body,center=false}:{kicker:string,title:string,body?:string,center?:boolean}) { return <div className={`heading ${center ? 'center' : ''}`}><p className="kicker">{kicker}</p><h2>{title}</h2>{body && <p>{body}</p>}</div>; }
function StepNumber({number,side}:{number:string,side:'left'|'right'}) { return <div className={`stepNumber ${side}`}><span/><strong>{number}</strong><span/></div>; }

function Concierge({lang}:{lang:Lang}) {
  const c = conciergeContent[lang];
  return <section className="section concierge"><div className="conciergeIntro"><p className="kicker">{c.kicker}</p><h2>{c.title}</h2><p>{c.body}</p></div><div className="conciergeGrid">{c.items.map((item,i) => <article key={item}><span>{String(i+1).padStart(2,'0')}</span><p>{item}</p></article>)}</div></section>;
}

function ClientTools({lang}:{lang:Lang}) {
  const c = toolContent[lang];
  const [active,setActive] = useState(0);
  const [reportItem,setReportItem] = useState(0);
  const [arrivalItems,setArrivalItems] = useState<string[]>([]);
  const whatsapp = (message:string) => window.open(`https://wa.me/385915033936?text=${encodeURIComponent(message)}`,'_blank','noopener,noreferrer');
  const submitInquiry = (event:FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); whatsapp(`Boat Care Pula enquiry\nMarina: ${form.get('marina')}\nBoat length: ${form.get('length')}\nSchedule: ${form.get('rhythm')}\nNext arrival: ${form.get('arrival') || c.optional}\nNote: ${form.get('note') || c.optional}`); };
  const submitArrival = (event:FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); whatsapp(`Boat Care Pula pre-arrival request\nArrival: ${form.get('arrivalDate')}\nPlease prepare: ${arrivalItems.join(', ') || c.optional}\nNote: ${form.get('shopping') || c.optional}`); };
  return <section className="section clientTools" id="tools"><Heading kicker={c.kicker} title={c.title} body={c.body}/><div className="toolTabs" role="tablist">{c.tabs.map((tab,i) => <button key={tab} className={active === i ? 'active' : ''} onClick={() => setActive(i)} role="tab" aria-selected={active === i}>{tab}</button>)}</div><div className="toolPanel">
    {active === 0 && <form className="toolForm" onSubmit={submitInquiry}><h3>{c.inquiryTitle}</h3><div className="formGrid"><label>{c.marina}<select name="marina">{c.marinas.map(x => <option key={x}>{x}</option>)}</select></label><label>{c.length}<input name="length" type="text" placeholder="10.5 m" required/></label><label>{c.rhythm}<select name="rhythm">{c.rhythms.map(x => <option key={x}>{x}</option>)}</select></label><label>{c.arrival}<input name="arrival" type="date"/></label></div><label>{c.note}<textarea name="note" rows={3} placeholder={c.optional}/></label><button className="toolAction" type="submit"><Send/>{c.send}</button></form>}
    {active === 1 && <div className="interactiveReport"><div><span className="demoLabel">{c.sample}</span><h3>{c.reportTitle}</h3><p>{c.reportMeta}</p><small>{c.reportInfo}</small></div><div className="reportList">{c.reportRows.map(([label,value],i) => <button key={label} className={reportItem === i ? 'active' : ''} onClick={() => setReportItem(i)}><span>{label}</span><strong><Check/>{value}</strong></button>)}</div><p className="reportDetail">{c.reportDetails[reportItem]}</p></div>}
    {active === 2 && <form className="toolForm" onSubmit={submitArrival}><h3>{c.arrivalTitle}</h3><label>{c.arrivalDate}<input name="arrivalDate" type="date" required/></label><div className="requestChecks">{c.arrivalItems.map(item => <label key={item}><input type="checkbox" checked={arrivalItems.includes(item)} onChange={() => setArrivalItems(items => items.includes(item) ? items.filter(x => x !== item) : [...items,item])}/><span><Check/>{item}</span></label>)}</div><label>{c.shopping}<textarea name="shopping" rows={4} placeholder={c.optional}/></label><button className="toolAction" type="submit"><CalendarCheck/>{c.request}</button></form>}
    {active === 3 && <div className="approvalTool"><FileCheck2/><p className="demoLabel">{c.estimate}</p><h3>{c.approvalTitle}</h3><div><strong>{c.issue}</strong><span>{c.price}</span></div><button className="toolAction" onClick={() => whatsapp(`Boat Care Pula\nApproved: ${c.issue}\n${c.price}`)}><Check/>{c.approve}</button><a href="tel:+385915033936">{c.discuss}</a></div>}
    {active === 4 && <div className="historyTool"><div><History/><span><b>{c.historyTitle}</b><small>{c.historyNote}</small></span></div><ol>{c.history.map(([date,title,note]) => <li key={`${date}${title}`}><time>{date}</time><span><strong>{title}</strong><small>{note}</small></span></li>)}</ol></div>}
  </div></section>;
}
